export const unAuthorizedProtectedPaths = [
	"/setup-profile",
	"/update-password",
	"/user-dashboard",
	"/business-dashboard",
	"/practitioner-dashboard",
	"/rtc/video-call",
]
export const practitionerCategories = [
	{
		category: "Doctor",
		subCategories: [
			"Anesthesiologists",
			"Audiology",
			"Cardiac surgeons",
			"Cardiologists",
			"hiropractic",
			"Dentist",
			"Dermatologists",
			"Endocrinologists",
			"Family Medicine",
			"Gastroenterologists",
			"General surgeons",
			"Geriatric medicine",
			"Homeopathy",
			"Infectious disease",
			"Internal medicine",
			"Medicine",
			"Nephrologists",
			"Neurologists",
			"Nutritionist",
			"Obstetrician/gynecologist",
			"Oncologists",
			"Ophthalmologists",
			"Orthopedic surgeons",
			"Otolaryngologists",
			"Pediatrics",
			"Periodontology",
			"Podiatry",
			"Psychiatrists",
			"Pulmonologists",
			"Radiologists",
			"Rheumatologists",
			"Urologists",
			"Veterinarians",
		],
	},
	{
		category: "Lawyer",
		subCategories: [
			"Bankruptcy Lawyer",
			"Civil Litigation Lawyer",
			"Contract Lawyer",
			"Corporate Lawyer",
			"Criminal Lawyer",
			"Employment Lawyer",
			"Estate Planning Lawyer",
			"Family Lawyer",
			"General Practice Lawyer",
			"Immigration Lawyer",
			"Intellectual Property Lawyer",
			"Medical Malpractice Lawyer",
			"Personal Injury Lawyer",
			"Social Security Disability Lawyer",
			"Tax Lawyer",
			"Worker's Compensation Lawyer",
		],
	},
	{
		category: "Consultant",
		subCategories: [
			"Financial Advisory",
			"Human Resource",
			"Information Technology",
			"Management",
			"Operations",
			"Strategy",
		],
	},
	{
		category: "Analyst",
		subCategories: [
			"Business",
			"Computer systems",
			"Data",
			"Economic",
			"Financial",
			"Geospatial",
			"Intelligence",
			"Management",
			"Network",
			"Operations",
			"Program",
			"Project",
			"Tax",
			"Technical",
			"Vendor",
		],
	},
	{ category: "Advisor", subCategories: ["Business", "Financial", "Legal"] },
	{
		category: "Therapist",
		subCategories: [
			"Acupuncture",
			"Art",
			"Athletic",
			"Cognitive-behavioral",
			"Dialectical behavioral",
			"Exposure",
			"Family ",
			"Group",
			"Humanistic",
			"Interpersonal",
			"Marriage and family",
			"Message",
			"Mindfulness-based",
			"Physio",
			"Psychodynamic",
			"Somatic psychotherapy",
			"Speech",
		],
	},
	{
		category: "Finance",
		subCategories: [
			"Corporate",
			"Financial planning and advising",
			"Banking",
			"Accounting",
			"Investment",
			"Insurance",
		],
	},
	{
		category: "Broker",
		subCategories: [
			"Stocks",
			"Credit",
			"Real Estate",
			"Business",
			"Forex",
			"Insurance",
			"Prime",
			"Futures",
			"Retirement Accounts",
			"Cryptocurrency",
		],
	},
];
export const organizationCategories = [
	{
		category: "Agency",
		subCategories: [
			"Advertising",
			"Branding",
			"Creative Agency or Design Firm",
			"Event management",
			"Digital",
			"Freelancers",
			"Marketing",
			"Media",
			"Promotional",
			"Public Relations",
			"Travel",
		],
	},
	{
		category: "Health Care",
		subCategories: ["Hospital", "Clinic", "Yoga", "Fitness"],
	},
	{
		category: "Firm",
		subCategories: [
			" Lawyer firm",
			"Consultancy firm",
			"Architecture",
			"IT",
			"Brokerage",
		],
	},
	{ category: "Institute", subCategories: ["Teaching", "Training"] },
	{ category: "Beauty", subCategories: ["Med Spa", "Saloon", "Spa"] },
];
export const businessTypes = ["Solo", "Multiple"];

export const yourRole = ["Practitioner", "Adminstrator", "Both"];
