export const setUpOptions = [
	{
		id: 1,
		title: "Account Recommendations",
		icon: "recom",
		slug: "settings_business",
	},
	{
		id: 2,
		title: "Subscriptions",
		icon: "subscription",
		slug: "settings_offerings",
	},
	{
		id: 3,
		title: "Organization Info",
		icon: "organization",
		slug: "settings_business",
	},
	{
		id: 4,
		title: "Branding",
		icon: "branding",
		slug: "settings_offerings",
	},
	{
		id: 5,
		title: "Email",
		icon: "email",
		slug: "settings_email",
	},
	{
		id: 6,
		title: "Online Booking",
		icon: "booking",
		slug: "settings_offerings",
	},
	{
		id: 7,
		title: "Reminder and Notifications",
		icon: "notification1",
		slug: "settings_business",
	},
	{
		id: 8,
		title: "Schedule",
		icon: "schedule",
		slug: "settings_appointmentSchedule",
	},
	{
		id: 9,
		title: "Rating and Reviews",
		icon: "ratings",
		slug: "settings_ratings",
	},
	{
		id: 10,
		title: "Intake form",
		icon: "intake",
		slug: "settings_eforms",
	},
	{
		id: 11,
		title: "Departments",
		icon: "departments",
		slug: "settings_offerings",
	},
	{
		id: 12,
		title: "Services and Class",
		icon: "service",
		slug: "settings_offerings",
	},
	{
		id: 13,
		title: "Website Widgets",
		icon: "widget",
		slug: "settings_widgets",
	},
	{
		id: 14,
		title: "Membership and packages",
		icon: "packages",
		slug: "settings_offerings",
	},
	{
		id: 15,
		title: "Global practices",
		icon: "global",
		slug: "settings_global",
	},
	{
		id: 16,
		title: "Google setup",
		icon: "google",
		slug: "settings_google",
	},
	{
		id: 17,
		title: "Integration",
		icon: "intrigration",
		slug: "settings_intregrations",
	},
	{
		id: 18,
		title: "Backup and storage",
		icon: "backup",
		slug: "settings_backup",
	},
];
