const AppointmentTableTab = [
  {
    id: "1",
    date: "02.11.2020",
    time: "10.00am",
    service: "General consultant",
    staff: "Delware",
    type: "Online",
    payment: "$60 (Paid)",
  },
  {
    id: "2",
    date: "02.11.2020",
    time: "10.00am",
    service: "General consultant",
    staff: "Delware",
    type: "Online",
    payment: "$60 (Unpaid)",
  },
  {
    id: "3",
    date: "02.11.2020",
    time: "10.00am",
    service: "General consultant",
    staff: "Delware",
    type: "Online",
    payment: "$60 (Partial)",
  },
  {
    id: "4",
    date: "02.11.2020",
    time: "10.00am",
    service: "General consultant",
    staff: "Delware",
    type: "Online",
    payment: "$60 (Paid)",
  },
  {
    id: "5",
    date: "02.11.2020",
    time: "10.00am",
    service: "General consultant",
    staff: "Delware",
    type: "Online",
    payment: "$60 (Paid)",
  },
  {
    id: "6",
    date: "02.11.2020",
    time: "10.00am",
    service: "General consultant",
    staff: "Delware",
    type: "Online",
    payment: "$60 (Unpaid)",
  },
];
export default AppointmentTableTab;
