const CaseTableTabInfo = [
  {
    id: "1",
    case: "Case 1",
    date: "22.11.2020",
    appoinment: "General consultant (CI)",
    staff: "Delware",
    solution: "Prescription",
    documents: "7 files",
  },
  {
    id: "2",
    case: "Case 2",
    date: "22.11.2020",
    appoinment: "General consultant (CI)",
    staff: "Delware",
    solution: "Chart",
    documents: "11 files",
  },
  {
    id: "3",
    case: "Case 3",
    date: "22.11.2020",
    appoinment: "General consultant (CI)",
    staff: "Delware",
    solution: "Document",
    documents: "2 files",
  },
  {
    id: "4",
    case: "Case 4",
    date: "22.11.2020",
    appoinment: "General consultant (CI)",
    staff: "Delware",
    solution: "  -  ",
    documents: "2 files",
  },
  {
    id: "5",
    case: "Case 5",
    date: "22.11.2020",
    appoinment: "General consultant (CI)",
    staff: "Delware",
    solution: "  -  ",
    documents: "2 files",
  },
  {
    id: "6",
    case: "Case 5",
    date: "22.11.2020",
    appoinment: "General consultant (CI)",
    staff: "Delware",
    solution: "  -  ",
    documents: "2 files",
  },
  {
    id: "7",
    case: "Case 5",
    date: "22.11.2020",
    appoinment: "General consultant (CI)",
    staff: "Delware",
    solution: "  -  ",
    documents: "2 files",
  },
];
export default CaseTableTabInfo;
