const PaymnetTableTabInfo = [
  {
    id: "1",
    invoice: "#1212",
    date: "02.11.2020",
    service: "General consultant",
    staff: "Delware",
    status: "Unpaid",
    amount: "$60 (Paid)",
  },
  {
    id: "2",
    invoice: "#1212",
    date: "02.11.2020",
    service: "General consultant",
    staff: "Delware",
    status: "Processing",
    amount: "$60 (Paid)",
  },
  {
    id: "3",
    invoice: "#1212",
    date: "02.11.2020",
    service: "General consultant",
    staff: "Delware",
    status: "Paid",
    amount: "$60 (Paid)",
  },
  {
    id: "4",
    invoice: "#1212",
    date: "02.11.2020",
    service: "General consultant",
    staff: "Delware",
    status: "Pending",
    amount: "$60 (Paid)",
  },
  {
    id: "5",
    invoice: "#1212",
    date: "02.11.2020",
    service: "General consultant",
    staff: "Delware",
    status: "Paid",
    amount: "$60 (Paid)",
  },
  {
    id: "6",
    invoice: "#1212",
    date: "02.11.2020",
    service: "General consultant",
    staff: "Delware",
    status: "Paid",
    amount: "$60 (Paid)",
  },
];
export default PaymnetTableTabInfo;
