const ActivityReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    activityname: "Md. Tazul Islam",
    doneby: "Md. Delwar Hossain",
    action: [
      "Book an appointment for",
      "Md. Delwar Hossain",
      "Appointment in 24 Feb 2022 ,10.00 AM for Service name",
    ],
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    activityname: "Md. Tazul Islam",
    doneby: "Md. Delwar Hossain",
    action: [
      "Book an appointment for",
      "Md. Delwar Hossain",
      "Appointment in 24 Feb 2022 ,10.00 AM for Service name",
    ],
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    activityname: "Md. Tazul Islam",
    doneby: "Md. Delwar Hossain",
    action: [
      "Book an appointment for",
      "Md. Delwar Hossain",
      "Appointment in 24 Feb 2022 ,10.00 AM for Service name",
    ],
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    activityname: "Md. Tazul Islam",
    doneby: "Md. Delwar Hossain",
    action: [
      "Book an appointment for",
      "Md. Delwar Hossain",
      "Appointment in 24 Feb 2022 ,10.00 AM for Service name",
    ],
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    activityname: "Md. Tazul Islam",
    doneby: "Md. Delwar Hossain",
    action: [
      "Book an appointment for",
      "Md. Delwar Hossain",
      "Appointment in 24 Feb 2022 ,10.00 AM for Service name",
    ],
  },
  {
    id: 6,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    activityname: "Md. Tazul Islam",
    doneby: "Md. Delwar Hossain",
    action: [
      "Book an appointment for",
      "Md. Delwar Hossain",
      "Appointment in 24 Feb 2022 ,10.00 AM for Service name",
    ],
  },
  {
    id: 7,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    activityname: "Md. Tazul Islam",
    doneby: "Md. Delwar Hossain",
    action: [
      "Book an appointment for",
      "Md. Delwar Hossain",
      "Appointment in 24 Feb 2022 ,10.00 AM for Service name",
    ],
  },
  {
    id: 8,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    activityname: "Md. Tazul Islam",
    doneby: "Md. Delwar Hossain",
    action: [
      "Book an appointment for",
      "Md. Delwar Hossain",
      "Appointment in 24 Feb 2022 ,10.00 AM for Service name",
    ],
  },
];
export default ActivityReportInfo;
