export const AppointmentReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customerName: "Zhalok Rahman",
    practitionerName: "Dr Md Tazrul Islam",
    BookingType: "General Consultancy",
    BookingPrice: "$30 (Prepaid)",
    BookingMedium: "Offline",
    callDuration: "10.20",
    status: "Completed",
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customerName: "Zhalok Rahman",
    practitionerName: "Dr Md Tazrul Islam",
    BookingType: "General Consultancy",
    BookingPrice: "$30 (Prepaid)",
    BookingMedium: "Online",
    callDuration: "10.20",
    status: "Completed",
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customerName: "Zhalok Rahman",
    practitionerName: "Dr Md Nazrul Islam",
    BookingType: "General Consultancy",
    BookingPrice: "$30 (Prepaid)",
    BookingMedium: "Offline",
    callDuration: "10.20",
    status: "Completed",
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customerName: "Zhalok Rahman",
    practitionerName: "Dr Md Nazrul Islam",
    BookingType: "General Consultancy",
    BookingPrice: "$30 (Prepaid)",
    BookingMedium: "Online",
    callDuration: "10.20",
    status: "Completed",
  },
];
