const DueAmountReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    invoiceNo: "#0001",
    customername: "Md. Tazul Islam",
    serviceName: "General Consultancy",
    doneby: "Md. Delwar Hossain",
    paidAmount: "$30",
    dueAmount: "$40",
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    invoiceNo: "#0001",
    customername: "Md. Tazul Islam",
    serviceName: "General Consultancy",
    doneby: "Md. Delwar Hossain",
    paidAmount: "$30",
    dueAmount: "$40",
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    invoiceNo: "#0001",
    customername: "Md. Tazul Islam",
    serviceName: "General Consultancy",
    doneby: "Md. Delwar Hossain",
    paidAmount: "$30",
    dueAmount: "$40",
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    invoiceNo: "#0001",
    customername: "Md. Tazul Islam",
    serviceName: "General Consultancy",
    doneby: "Md. Delwar Hossain",
    paidAmount: "$30",
    dueAmount: "$40",
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    invoiceNo: "#0001",
    customername: "Md. Tazul Islam",
    serviceName: "General Consultancy",
    doneby: "Md. Delwar Hossain",
    paidAmount: "$30",
    dueAmount: "$40",
  },
  {
    id: 6,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    invoiceNo: "#0001",
    customername: "Md. Tazul Islam",
    serviceName: "General Consultancy",
    doneby: "Md. Delwar Hossain",
    paidAmount: "$30",
    dueAmount: "$40",
  },
  {
    id: 7,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    invoiceNo: "#0001",
    customername: "Md. Tazul Islam",
    serviceName: "General Consultancy",
    doneby: "Md. Delwar Hossain",
    paidAmount: "$30",
    dueAmount: "$40",
  },
  {
    id: 8,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    invoiceNo: "#0001",
    customername: "Md. Tazul Islam",
    serviceName: "General Consultancy",
    doneby: "Md. Delwar Hossain",
    paidAmount: "$30",
    dueAmount: "$40",
  },
];
export default DueAmountReportInfo;
