const PackageReportInfo = [
  {
    id: 1,
    name: "Package 1",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 2,
    name: "Package 1",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 3,
    name: "Package 1",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 4,
    name: "Package 1",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 5,
    name: "Package 1",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 6,
    name: "Package 1",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 7,
    name: "Package 1",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 8,
    name: "Package 1",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
];

export default PackageReportInfo;
