const PractionerReportInfo = [
  {
    id: 1,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
  {
    id: 2,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
  {
    id: 3,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
  {
    id: 4,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
  {
    id: 5,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
  {
    id: 6,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
  {
    id: 7,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
  {
    id: 8,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
  {
    id: 9,
    name: "Md. Tazrul Islam",
    BookingHour: "19.5 Hours",
    totalappointment: "122",
    totalcancel: "23",
    totalvideocall: "190 Hrs",
    totalaudiocall: "23 Hrs",
    mostsell: "General Consultancy 33times ($2.7k)",
    mostvalue: "General Consultancy 33times ($2.7k)",
  },
];

export default PractionerReportInfo;
