const PaymentReportInfo = [
  {
    id: 1,
    date: "02 July, 1999",
    branch: "Dhaka",
    stuffname: "Md. Tazrul Islam",
    type: "Commission",
    amount: "$122",
    received: "$24",
  },
  {
    id: 2,
    date: "02 July, 1999",
    branch: "Dhaka",
    stuffname: "Md. Tazrul Islam",
    type: "Commission",
    amount: "$122",
    received: "$24",
  },
  {
    id: 3,
    date: "02 July, 1999",
    branch: "Dhaka",
    stuffname: "Md. Tazrul Islam",
    type: "Commission",
    amount: "$122",
    received: "$24",
  },
  {
    id: 4,
    date: "02 July, 1999",
    branch: "Dhaka",
    stuffname: "Md. Tazrul Islam",
    type: "Commission",
    amount: "$122",
    received: "$24",
  },
  {
    id: 5,
    date: "02 July, 1999",
    branch: "Dhaka",
    stuffname: "Md. Tazrul Islam",
    type: "Commission",
    amount: "$122",
    received: "$24",
  },
  {
    id: 6,
    date: "02 July, 1999",
    branch: "Dhaka",
    stuffname: "Md. Tazrul Islam",
    type: "Commission",
    amount: "$122",
    received: "$24",
  },
  {
    id: 7,
    date: "02 July, 1999",
    branch: "Dhaka",
    stuffname: "Md. Tazrul Islam",
    type: "Commission",
    amount: "$122",
    received: "$24",
  },
  {
    id: 8,
    date: "02 July, 1999",
    branch: "Dhaka",
    stuffname: "Md. Tazrul Islam",
    type: "Commission",
    amount: "$122",
    received: "$24",
  },
];

export default PaymentReportInfo;
