const ProductReportInfo = [
  {
    id: 1,
    productname: "Yogo Mat 2XL",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 2,
    productname: "Yogo Mat 2XL",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 3,
    productname: "Yogo Mat 2XL",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 4,
    productname: "Yogo Mat 2XL",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 5,
    productname: "Yogo Mat 2XL",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 6,
    productname: "Yogo Mat 2XL",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 7,
    productname: "Yogo Mat 2XL",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
  {
    id: 8,
    productname: "Yogo Mat 2XL",
    branch: "Dhaka",
    price: "$30",
    totalsell: "120",
    mostbuyingcustomer: ["Md. Tazrul Islamn", "10"],
    mostsellingpractitioner: ["Md. Delowar Hossain", "7"],
  },
];

export default ProductReportInfo;
