export const reportsItem = [
  {
    id: 1,
    title: "Appointment",
    icon: "appointment",
    iconHeight: 33,
    iconWidth: 33,
  },
  {
    id: 2,
    title: "Sales Summary",
    icon: "salesummary",
    iconHeight: 36,
    iconWidth: 36,
  },
  {
    id: 3,
    title: "Sales",
    icon: "sales",
    iconHeight: 30,
    iconWidth: 30,
  },
  {
    id: 4,
    title: "Due Amount",
    icon: "due",
    iconHeight: 38,
    iconWidth: 36,
  },
  {
    id: 5,
    title: "Customer",
    icon: "customers",
    iconHeight: 32,
    iconWidth: 34,
  },
  {
    id: 6,
    title: "Email",
    icon: "email",
    iconHeight: 28,
    iconWidth: 30,
  },
  {
    id: 7,
    title: "Practitioner",
    icon: "practitioner",
    iconHeight: 33,
    iconWidth: 33,
  },
  {
    id: 8,
    title: "Staff",
    icon: "staff",
    iconHeight: 33,
    iconWidth: 33,
  },
  {
    id: 9,
    title: "Payment",
    icon: "payment",
    iconHeight: 33,
    iconWidth: 33,
  },
  {
    id: 10,
    title: "Product",
    icon: "product",
    iconHeight: 36,
    iconWidth: 36,
  },
  {
    id: 11,
    title: "Services",
    icon: "services",
    iconHeight: 36,
    iconWidth: 36,
  },
  {
    id: 12,
    title: "Packages and Membership",
    icon: "package",
    iconHeight: 33,
    iconWidth: 33,
  },
  {
    id: 13,
    title: "Transactions",
    icon: "transections",
    iconHeight: 33,
    iconWidth: 36,
  },
  {
    id: 14,
    title: "Fees",
    icon: "fees",
    iconHeight: 36,
    iconWidth: 33,
  },
  {
    id: 15,
    title: "Waitlist",
    icon: "waitlist",
    iconHeight: 33,
    iconWidth: 33,
  },
  {
    id: 16,
    title: "Request List",
    icon: "request",
    iconHeight: 36,
    iconWidth: 36,
  },
  {
    id: 17,
    title: "Video and Audio List",
    icon: "video",
    iconHeight: 30,
    iconWidth: 36,
  },
  {
    id: 18,
    title: "Reviews",
    icon: "reviews",
    iconHeight: 36,
    iconWidth: 32,
  },
  {
    id: 19,
    title: "Support",
    icon: "support",
    iconHeight: 36,
    iconWidth: 36,
  },
  {
    id: 20,
    title: "Activity",
    icon: "activity",
    iconHeight: 33,
    iconWidth: 33,
  },
];
