const RequestlistReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    timerange: "10.00 AM - 11.00 AM",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    requestfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    action: "Rejected",
    note: "This is note",
    status: "Rejected",
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    timerange: "10.00 AM - 11.00 AM",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    requestfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    action: "Rejected",
    note: "This is note",
    status: "Rejected",
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    timerange: "10.00 AM - 11.00 AM",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    requestfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    action: "Rejected",
    note: "This is note",
    status: "Rejected",
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    timerange: "10.00 AM - 11.00 AM",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    requestfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    action: "Rejected",
    note: "This is note",
    status: "Rejected",
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    timerange: "10.00 AM - 11.00 AM",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    requestfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    action: ["Proposed 2 July 2022", "11:00 AM - 12:00 AM", "Message On"],
    note: "This is note",
    status: "Rejected",
  },
  {
    id: 6,
    date: "10 Aug, 2022",
    timerange: "10.00 AM - 11.00 AM",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    requestfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    action: ["Override On", "Delwar Hossain", "Message On "],
    note: "This is note",
    status: "Rejected",
  },
  {
    id: 7,
    date: "10 Aug, 2022",
    timerange: "10.00 AM - 11.00 AM",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    requestfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    action: "Rejected",
    note: "This is note",
    status: "Approved",
  },
  {
    id: 8,
    date: "10 Aug, 2022",
    timerange: "10.00 AM - 11.00 AM",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    requestfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    action: "Rejected",
    note: "This is note",
    status: "Approved",
  },
];
export default RequestlistReportInfo;
