const ReviewReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    servicename: "General Consultancy",
    staffname: "Abdul Kader Akash",
    rating: "4.3",
    description: "This is Description",
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    servicename: "General Consultancy",
    staffname: "Abdul Kader Akash",
    rating: "4.3",
    description: "This is Description",
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    servicename: "General Consultancy",
    staffname: "Abdul Kader Akash",
    rating: "4.3",
    description: "This is Description",
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    servicename: "General Consultancy",
    staffname: "Abdul Kader Akash",
    rating: "4.3",
    description: "This is Description",
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    servicename: "General Consultancy",
    staffname: "Abdul Kader Akash",
    rating: "4.3",
    description: "This is Description",
  },
  {
    id: 6,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    servicename: "General Consultancy",
    staffname: "Abdul Kader Akash",
    rating: "4.3",
    description: "This is Description",
  },
  {
    id: 7,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    servicename: "General Consultancy",
    staffname: "Abdul Kader Akash",
    rating: "4.3",
    description: "This is Description",
  },
  {
    id: 8,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    servicename: "General Consultancy",
    staffname: "Abdul Kader Akash",
    rating: "4.3",
    description: "This is Description",
  },
];
export default ReviewReportInfo;
