const SalesReportInfo = [
  {
    id: 1,
    invoiceno: "#000001",
    date: "10 Jan ,2023",
    time: "10.00 (EDT)",
    branch: "Dhaka",
    itemname: "Consultancy",
    quantity: "1",
    customername: "Md. Tazrul Islam",
    staff: "Delowar Hossen",
    price: "$10",
    ambelfee: "$1",
    discount: "$2",
    shipping: "$2",
    tax: "$2",
    total: "$10",
    status: "Comlete",
  },
  {
    id: 2,
    invoiceno: "#000001",
    date: "10 Jan ,2023",
    time: "10.00 (EDT)",
    branch: "Dhaka",
    itemname: "Consultancy",
    quantity: "1",
    customername: "Md. Tazrul Islam",
    staff: "Delowar Hossen",
    price: "$10",
    ambelfee: "$1",
    discount: "$2",
    shipping: "$2",
    tax: "$2",
    total: "$10",
    status: "Comlete",
  },
  {
    id: 3,
    invoiceno: "#000001",
    date: "10 Jan ,2023",
    time: "10.00 (EDT)",
    branch: "Dhaka",
    itemname: "Consultancy",
    quantity: "1",
    customername: "Md. Tazrul Islam",
    staff: "Delowar Hossen",
    price: "$10",
    ambelfee: "$1",
    discount: "$2",
    shipping: "$2",
    tax: "$2",
    total: "$10",
    status: "Comlete",
  },
  {
    id: 4,
    invoiceno: "#000001",
    date: "10 Jan ,2023",
    time: "10.00 (EDT)",
    branch: "Dhaka",
    itemname: "Consultancy",
    quantity: "1",
    customername: "Md. Tazrul Islam",
    staff: "Delowar Hossen",
    price: "$10",
    ambelfee: "$1",
    discount: "$2",
    shipping: "$2",
    tax: "$2",
    total: "$10",
    status: "Comlete",
  },
  {
    id: 5,
    invoiceno: "#000001",
    date: "10 Jan ,2023",
    time: "10.00 (EDT)",
    branch: "Dhaka",
    itemname: "Consultancy",
    quantity: "1",
    customername: "Md. Tazrul Islam",
    staff: "Delowar Hossen",
    price: "$10",
    ambelfee: "$1",
    discount: "$2",
    shipping: "$2",
    tax: "$2",
    total: "$10",
    status: "Comlete",
  },
  {
    id: 6,
    invoiceno: "#000001",
    date: "10 Jan ,2023",
    time: "10.00 (EDT)",
    branch: "Dhaka",
    itemname: "Consultancy",
    quantity: "1",
    customername: "Md. Tazrul Islam",
    staff: "Delowar Hossen",
    price: "$10",
    ambelfee: "$1",
    discount: "$2",
    shipping: "$2",
    tax: "$2",
    total: "$10",
    status: "Comlete",
  },
  {
    id: 7,
    invoiceno: "#000001",
    date: "10 Jan ,2023",
    time: "10.00 (EDT)",
    branch: "Dhaka",
    itemname: "Consultancy",
    quantity: "1",
    customername: "Md. Tazrul Islam",
    staff: "Delowar Hossen",
    price: "$10",
    ambelfee: "$1",
    discount: "$2",
    shipping: "$2",
    tax: "$2",
    total: "$10",
    status: "Comlete",
  },
  {
    id: 8,
    invoiceno: "#000001",
    date: "10 Jan ,2023",
    time: "10.00 (EDT)",
    branch: "Dhaka",
    itemname: "Consultancy",
    quantity: "1",
    customername: "Md. Tazrul Islam",
    staff: "Delowar Hossen",
    price: "$10",
    ambelfee: "$1",
    discount: "$2",
    shipping: "$2",
    tax: "$2",
    total: "$10",
    status: "Comlete",
  },
];

export default SalesReportInfo;
