const ServiceReportInfo = [
  {
    id: 1,
    servicename: "General Consultancy",
    practitionername: "Md. Delowar Hossain",
    branch: "Dhaka",
    price: "$120",
    totalsell: "$1234",
    mostbuyingcustomer: ["Md. Delowar Hossain", "20"],
  },
  {
    id: 2,
    servicename: "General Consultancy",
    practitionername: "Md. Delowar Hossain",
    branch: "Dhaka",
    price: "$120",
    totalsell: "$1234",
    mostbuyingcustomer: ["Md. Delowar Hossain", "20"],
  },
  {
    id: 3,
    servicename: "General Consultancy",
    practitionername: "Md. Delowar Hossain",
    branch: "Dhaka",
    price: "$120",
    totalsell: "$1234",
    mostbuyingcustomer: ["Md. Delowar Hossain", "20"],
  },
  {
    id: 4,
    servicename: "General Consultancy",
    practitionername: "Md. Delowar Hossain",
    branch: "Dhaka",
    price: "$120",
    totalsell: "$1234",
    mostbuyingcustomer: ["Md. Delowar Hossain", "20"],
  },
  {
    id: 5,
    servicename: "General Consultancy",
    practitionername: "Md. Delowar Hossain",
    branch: "Dhaka",
    price: "$120",
    totalsell: "$1234",
    mostbuyingcustomer: ["Md. Delowar Hossain", "20"],
  },
  {
    id: 6,
    servicename: "General Consultancy",
    practitionername: "Md. Delowar Hossain",
    branch: "Dhaka",
    price: "$120",
    totalsell: "$1234",
    mostbuyingcustomer: ["Md. Delowar Hossain", "20"],
  },
  {
    id: 7,
    servicename: "General Consultancy",
    practitionername: "Md. Delowar Hossain",
    branch: "Dhaka",
    price: "$120",
    totalsell: "$1234",
    mostbuyingcustomer: ["Md. Delowar Hossain", "20"],
  },
  {
    id: 8,
    servicename: "General Consultancy",
    practitionername: "Md. Delowar Hossain",
    branch: "Dhaka",
    price: "$120",
    totalsell: "$1234",
    mostbuyingcustomer: ["Md. Delowar Hossain", "20"],
  },
];

export default ServiceReportInfo;
