const StuffReportInfo = [
  {
    id: 1,
    name: "Md. Tazrul Islam",
    branch: "Dhaka",
    Employed: "02 June, 1998",
    totalactivetime: "23.5 Hours",
    taskcomlete: "122",
    taskfailed: "34",
  },
  {
    id: 2,
    name: "Md. Tazrul Islam",
    branch: "Dhaka",
    Employed: "02 June, 1998",
    totalactivetime: "23.5 Hours",
    taskcomlete: "122",
    taskfailed: "34",
  },
  {
    id: 3,
    name: "Md. Tazrul Islam",
    branch: "Dhaka",
    Employed: "02 June, 1998",
    totalactivetime: "23.5 Hours",
    taskcomlete: "122",
    taskfailed: "34",
  },
  {
    id: 4,
    name: "Md. Tazrul Islam",
    branch: "Dhaka",
    Employed: "02 June, 1998",
    totalactivetime: "23.5 Hours",
    taskcomlete: "122",
    taskfailed: "34",
  },
  {
    id: 5,
    name: "Md. Tazrul Islam",
    branch: "Dhaka",
    Employed: "02 June, 1998",
    totalactivetime: "23.5 Hours",
    taskcomlete: "122",
    taskfailed: "34",
  },
  {
    id: 6,
    name: "Md. Tazrul Islam",
    branch: "Dhaka",
    Employed: "02 June, 1998",
    totalactivetime: "23.5 Hours",
    taskcomlete: "122",
    taskfailed: "34",
  },
  {
    id: 7,
    name: "Md. Tazrul Islam",
    branch: "Dhaka",
    Employed: "02 June, 1998",
    totalactivetime: "23.5 Hours",
    taskcomlete: "122",
    taskfailed: "34",
  },
  {
    id: 8,
    name: "Md. Tazrul Islam",
    branch: "Dhaka",
    Employed: "02 June, 1998",
    totalactivetime: "23.5 Hours",
    taskcomlete: "122",
    taskfailed: "34",
  },
];

export default StuffReportInfo;
