const SupportReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    lookingfofr: "Md. Delwar Hossain",
    provider: "Md. Delwar Hossain",
    rating: "4.3",
    status: "Solved",
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    lookingfofr: "Md. Delwar Hossain",
    provider: "Md. Delwar Hossain",
    rating: "4.3",
    status: "Solved",
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    lookingfofr: "Md. Delwar Hossain",
    provider: "Md. Delwar Hossain",
    rating: "4.3",
    status: "Unsolved",
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    lookingfofr: "Md. Delwar Hossain",
    provider: "Md. Delwar Hossain",
    rating: "4.3",
    status: "Solved",
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    lookingfofr: "Md. Delwar Hossain",
    provider: "Md. Delwar Hossain",
    rating: "4.3",
    status: "Solved",
  },
  {
    id: 6,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    lookingfofr: "Md. Delwar Hossain",
    provider: "Md. Delwar Hossain",
    rating: "4.3",
    status: "Unsolved",
  },
  {
    id: 7,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    lookingfofr: "Md. Delwar Hossain",
    provider: "Md. Delwar Hossain",
    rating: "4.3",
    status: "Solved",
  },
  {
    id: 8,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    lookingfofr: "Md. Delwar Hossain",
    provider: "Md. Delwar Hossain",
    rating: "4.3",
    status: "Solved",
  },
];
export default SupportReportInfo;
