const TransactionReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    invoice: "#001",
    payer: "Md. Tazul Islam",
    reciver: "Md. Delwar Hossain",
    amount: "$40",
    type: ["Product Sell", "Product Full Name"],
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    invoice: "#001",
    payer: "Md. Tazul Islam",
    reciver: "Md. Delwar Hossain",
    amount: "$40",
    type: ["Service Sell", "Service Full Name"],
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    invoice: "#001",
    payer: "Md. Tazul Islam",
    reciver: "Md. Delwar Hossain",
    amount: "$40",
    type: ["Add Money", "Via ****3434 Card"],
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    invoice: "#001",
    payer: "Md. Tazul Islam",
    reciver: "Md. Delwar Hossain",
    amount: "$40",
    type: ["Send Money", "Staff Payment"],
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    invoice: "#001",
    payer: "Md. Tazul Islam",
    reciver: "Md. Delwar Hossain",
    amount: "$40",
    type: ["Refund", "Reason for refund"],
  },
  {
    id: 6,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    invoice: "#001",
    payer: "Md. Tazul Islam",
    reciver: "Md. Delwar Hossain",
    amount: "$40",
    type: ["Referred", "Akash"],
  },
  {
    id: 7,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    invoice: "#001",
    payer: "Md. Tazul Islam",
    reciver: "Md. Delwar Hossain",
    amount: "$40",
    type: ["Fee", "late Cancellation", "Service Name"],
  },
  {
    id: 8,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    invoice: "#001",
    payer: "Md. Tazul Islam",
    reciver: "Md. Delwar Hossain",
    amount: "$40",
    type: ["Product Sell", "Product Full Name"],
  },
];
export default TransactionReportInfo;
