const VideoandAudioReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    servicename: "General Consultancy",
    customername: "Md. Tazul Islam",
    practitionername: "Abdul Kader Akash",
    duration: "10.30 Min",
    type: "Video call",
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    servicename: "General Consultancy",
    customername: "Md. Tazul Islam",
    practitionername: "Abdul Kader Akash",
    duration: "10.30 Min",
    type: "Audio call",
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    servicename: "General Consultancy",
    customername: "Md. Tazul Islam",
    practitionername: "Abdul Kader Akash",
    duration: "10.30 Min",
    type: "Video call",
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    servicename: "General Consultancy",
    customername: "Md. Tazul Islam",
    practitionername: "Abdul Kader Akash",
    duration: "10.30 Min",
    type: "Audio call",
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    servicename: "General Consultancy",
    customername: "Md. Tazul Islam",
    practitionername: "Abdul Kader Akash",
    duration: "10.30 Min",
    type: "Audio call",
  },
  {
    id: 6,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    servicename: "General Consultancy",
    customername: "Md. Tazul Islam",
    practitionername: "Abdul Kader Akash",
    duration: "10.30 Min",
    type: "Video call",
  },
  {
    id: 7,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    servicename: "General Consultancy",
    customername: "Md. Tazul Islam",
    practitionername: "Abdul Kader Akash",
    duration: "10.30 Min",
    type: "Video call",
  },
  {
    id: 8,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    servicename: "General Consultancy",
    customername: "Md. Tazul Islam",
    practitionername: "Abdul Kader Akash",
    duration: "10.30 Min",
    type: "Video call",
  },
];
export default VideoandAudioReportInfo;
