const WaitlistReportInfo = [
  {
    id: 1,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    waitedfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    status: "Failed",
  },
  {
    id: 2,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    waitedfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    status: "Booked/P",
  },
  {
    id: 3,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    waitedfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    status: "Booked/R",
  },
  {
    id: 4,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    waitedfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    status: "Failed",
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    waitedfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    status: "Booked/P",
  },
  {
    id: 6,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    waitedfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    status: "Failed",
  },
  {
    id: 7,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    waitedfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    status: "Failed",
  },
  {
    id: 5,
    date: "10 Aug, 2022",
    time: "10.00 AM (EDT)",
    branch: "Dhaka",
    customername: "Md. Tazul Islam",
    waitedfor: "General Consultancy",
    practitionername: "Abdul Kader Akash",
    status: "Booked/R",
  },
];
export default WaitlistReportInfo;
