export const paymentItems = [
  {
    id: 1,
    title: "Balance",
    icon: "Balance",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 2,
    title: "Sales",
    icon: "Sales",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 3,
    title: "Staff payments",
    icon: "Staff_payment",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 4,
    title: "Transactions",
    icon: "Transections",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 5,
    title: "Fines",
    icon: "Fee",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 6,
    title: "Tax",
    icon: "Tax",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 7,
    title: "Discount",
    icon: "Discount",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 8,
    title: "Refund",
    icon: "Refund",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 9,
    title: "Staff Commission ",
    icon: "Commission",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 10,
    title: "Referral",
    icon: "Referral",
    iconHeight: 26,
    iconWidth: 36,
  },
  {
    id: 11,
    title: "Payment Settings",
    icon: "Payment_settings",
    iconHeight: 26,
    iconWidth: 36,
  },
];