export const FOO = "FOO";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ADD_ACTIVE_USER = "ADD_ACTIVE_USER";

export const HAS_TOKEN = "HAS_TOKEN";
export const LOADING = "LOADING";

export const USER_INFO_GET_SUCCESS = "USER_INFO_GET_SUCCESS";
export const USER_INFO_GET_FAIL = "USER_INFO_GET_FAIL";
export const USER_INFO_LOADING = "USER_INFO_POST_LOADING";

export const USER_INFO_POST_SUCCESS = "USER_INFO_POST_SUCCESS";
export const USER_INFO_POST_FAIL = "USER_INFO_POST_FAIL";

export const BUSINESS_INFO_GET_SUCCESS = "BUSINESS_INFO_GET_SUCCESS";
export const BUSINESS_INFO_GET_FAIL = "BUSINESS_INFO_GET_FAIL";
export const BUSINESS_INFO_LOADING = "BUSINESS_INFO_POST_LOADING";

export const BRANCH_INFO_GET_SUCCESS = "BRANCH_INFO_GET_SUCCESS";
export const BRANCH_INFO_GET_FAIL = "BRANCH_INFO_GET_FAIL";
export const BRANCH_INFO_LOADING = "BRANCH_INFO_POST_LOADING";
export const BRANCH_INFO_POST_SUCCESS = "BRANCH_INFO_POST_SUCCESS";
export const BRANCH_INFO_POST_FAIL = "BRANCH_INFO_POST_FAIL";

export const BUSINESS_INFO_POST_SUCCESS = "BUSINESS_INFO_POST_SUCCESS";
export const BUSINESS_INFO_POST_FAIL = "BUSINESS_INFO_POST_FAIL";

export const PRACTITIONER_INFO_GET_SUCCESS = "PRACTITIONER_INFO_GET_SUCCESS";
export const PRACTITIONER_INFO_GET_FAIL = "PRACTITIONER_INFO_GET_FAIL";
export const PRACTITIONER_INFO_LOADING = "PRACTITIONER_INFO_POST_LOADING";
export const PRACTITIONER_INFO_FILTER_SUCCESS =
  "PRACTITIONER_INFO_FILTER_SUCCESS";

export const PRACTITIONER_INFO_POST_SUCCESS = "PRACTITIONER_INFO_POST_SUCCESS";
export const PRACTITIONER_INFO_POST_FAIL = "PRACTITIONER_INFO_POST_FAIL";

export const EMAIL_FORMAT_GET_SUCCESS = "EMAIL_FORMAT_GET_SUCCESS";
export const EMAIL_FORMAT_GET_FAIL = "EMAIL_FORMAT_GET_FAIL";
export const EMAIL_FORMAT_LOADING = "EMAIL_FORMAT_POST_LOADING";

export const EMAIL_FORMAT_POST_SUCCESS = "EMAIL_FORMAT_POST_SUCCESS";
export const EMAIL_FORMAT_POST_FAIL = "EMAIL_FORMAT_POST_FAIL";

export const ONLINEBOOKING_GET_SUCCESS = "ONLINEBOOKING_GET_SUCCESS";
export const ONLINEBOOKING_GET_FAIL = "ONLINEBOOKING_GET_FAIL";
export const ONLINEBOOKING_LOADING = "ONLINEBOOKING_POST_LOADING";
export const ONLINEBOOKING_POST_SUCCESS = "ONLINEBOOKING_POST_SUCCESS";
export const ONLINEBOOKING_POST_FAIL = "ONLINEBOOKING_POST_FAIL";

export const SCHEDULESETTINGS_GET_SUCCESS = "SCHEDULESETTINGS_GET_SUCCESS";
export const SCHEDULESETTINGS_GET_FAIL = "SCHEDULESETTINGS_GET_FAIL";
export const SCHEDULESETTINGS_LOADING = "SCHEDULESETTINGS_POST_LOADING";
export const SCHEDULESETTINGS_POST_SUCCESS = "SCHEDULESETTINGS_POST_SUCCESS";
export const SCHEDULESETTINGS_POST_FAIL = "SCHEDULESETTINGS_POST_FAIL";

export const RATINGS_GET_SUCCESS = "RATINGS_GET_SUCCESS";
export const RATINGS_GET_FAIL = "RATINGS_GET_FAIL";
export const RATINGS_LOADING = "RATINGS_POST_LOADING";
export const RATINGS_POST_SUCCESS = "RATINGS_POST_SUCCESS";
export const RATINGS_POST_FAIL = "RATINGS_POST_FAIL";

export const DEPARTMENT_GET_SUCCESS = "DEPARTMENT_GET_SUCCESS";
export const DEPARTMENT_GET_FAIL = "DEPARTMENT_GET_FAIL";
export const DEPARTMENT_LOADING = "DEPARTMENT_POST_LOADING";
export const DEPARTMENT_POST_SUCCESS = "DEPARTMENT_POST_SUCCESS";
export const DEPARTMENT_POST_FAIL = "DEPARTMENT_POST_FAIL";

export const SERVICE_GET_SUCCESS = "SERVICE_GET_SUCCESS";
export const SERVICE_GET_FAIL = "SERVICE_GET_FAIL";
export const SERVICE_LOADING = "SERVICE_POST_LOADING";
export const SERVICE_POST_SUCCESS = "SERVICE_POST_SUCCESS";
export const SERVICE_POST_FAIL = "SERVICE_POST_FAIL";

export const FAMILYORGANIZATION_GET_SUCCESS = "FAMILYORGANIZATION_GET_SUCCESS";
export const FAMILYORGANIZATION_GET_FAIL = "FAMILYORGANIZATION_GET_FAIL";
export const FAMILYORGANIZATION_LOADING = "FAMILYORGANIZATION_POST_LOADING";
export const FAMILYORGANIZATION_POST_SUCCESS =
  "FAMILYORGANIZATION_POST_SUCCESS";
export const FAMILYORGANIZATION_POST_FAIL = "FAMILYORGANIZATION_POST_FAIL";

export const PACKAGEMEMBERSHIP_GET_SUCCESS = "PACKAGEMEMBERSHIP_GET_SUCCESS";
export const PACKAGEMEMBERSHIP_GET_FAIL = "PACKAGEMEMBERSHIP_GET_FAIL";
export const PACKAGEMEMBERSHIP_LOADING = "PACKAGEMEMBERSHIP_POST_LOADING";
export const PACKAGEMEMBERSHIP_POST_SUCCESS = "PACKAGEMEMBERSHIP_POST_SUCCESS";
export const PACKAGEMEMBERSHIP_POST_FAIL = "PACKAGEMEMBERSHIP_POST_FAIL";

export const FINDPROFESSIONAL_GET_SUCCESS = "FINDPROFESSIONAL_GET_SUCCESS";
export const FINDPROFESSIONAL_GET_FAIL = "FINDPROFESSIONAL_GET_FAIL";
export const FINDPROFESSIONAL_LOADING = "FINDPROFESSIONAL_POST_LOADING";
export const FINDPROFESSIONAL_POST_SUCCESS = "FINDPROFESSIONAL_POST_SUCCESS";
export const FINDPROFESSIONAL_POST_FAIL = "FINDPROFESSIONAL_POST_FAIL";

export const TASK_GET_SUCCESS = "TASK_GET_SUCCESS";
export const TASK_GET_FAIL = "TASK_GET_FAIL";
export const TASK_LOADING = "TASK_POST_LOADING";
export const TASK_POST_SUCCESS = "TASK_POST_SUCCESS";
export const TASK_POST_FAIL = "TASK_POST_FAIL";

export const STAFF_GET_SUCCESS = "STAFF_GET_SUCCESS";
export const STAFF_GET_FAIL = "STAFF_GET_FAIL";
export const STAFF_LOADING = "STAFF_POST_LOADING";
export const STAFF_POST_SUCCESS = "STAFF_POST_SUCCESS";
export const STAFF_POST_FAIL = "STAFF_POST_FAIL";

export const SINGLE_USER_GET_SUCCESS = "SINGLE_USER_GET_SUCCESS";
export const SINGLE_USER_GET_FAIL = "SINGLE_USER_GET_FAIL";
export const SINGLE_USER_LOADING = "SINGLE_USER_POST_LOADING";
export const SINGLE_USER_SUCCESS = "SINGLE_USER_POST_SUCCESS";
export const SINGLE_USER_FAIL = "SINGLE_USER_POST_FAIL";

export const USERFAMILYORG_GET_SUCCESS = "USERFAMILYORG_GET_SUCCESS";
export const USERFAMILYORG_GET_FAIL = "USERFAMILYORG_GET_FAIL";
export const USERFAMILYORG_LOADING = "USERFAMILYORG_POST_LOADING";
export const USERFAMILYORG_POST_SUCCESS = "USERFAMILYORG_POST_SUCCESS";
export const USERFAMILYORG_POST_FAIL = "USERFAMILYORG_POST_FAIL";
export const FAMILYORGMEMBER_GET_SUCCESS = "FAMILYORGMEMBER_GET_SUCCESS";
export const FAMILYORGMEMBER_GET_FAIL = "FAMILYORGMEMBER_GET_FAIL";
export const FAMILYORGMEMBER_LOADING = "FAMILYORGMEMBER_POST_LOADING";
export const FAMILYORGMEMBER_POST_SUCCESS = "FAMILYORGMEMBER_POST_SUCCESS";
export const FAMILYORGMEMBER_POST_FAIL = "FAMILYORGMEMBER_POST_FAIL";

export const USERREMINDER_GET_SUCCESS = "USERREMINDER_GET_SUCCESS";
export const USERREMINDER_GET_FAIL = "USERREMINDER_GET_FAIL";
export const USERREMINDER_LOADING = "USERREMINDER_POST_LOADING";
export const USERREMINDER_POST_SUCCESS = "USERREMINDER_POST_SUCCESS";
export const USERREMINDER_POST_FAIL = "USERREMINDER_POST_FAIL";

export const USERNOTIFICATION_GET_SUCCESS = "USERNOTIFICATION_GET_SUCCESS";
export const USERNOTIFICATION_GET_FAIL = "USERNOTIFICATION_GET_FAIL";
export const USERNOTIFICATION_LOADING = "USERNOTIFICATION_POST_LOADING";
export const USERNOTIFICATION_POST_SUCCESS = "USERNOTIFICATION_POST_SUCCESS";
export const USERNOTIFICATION_POST_FAIL = "USERNOTIFICATION_POST_FAIL";

export const USER_SCHEDULE_SETTING_GET_SUCCESS =
  "USER_SCHEDULE_SETTING_GET_SUCCESS";
export const USER_SCHEDULE_SETTING_GET_FAIL = "USER_SCHEDULE_SETTING_GET_FAIL";
export const USER_SCHEDULE_SETTING_LOADING =
  "USER_SCHEDULE_SETTING_POST_LOADING";
export const USER_SCHEDULE_SETTING_POST_SUCCESS =
  "USER_SCHEDULE_SETTING_POST_SUCCESS";
export const USER_SCHEDULE_SETTING_POST_FAIL =
  "USER_SCHEDULE_SETTING_POST_FAIL";

export const SCHEDULE_GET_SUCCESS = "SCHEDULE_GET_SUCCESS";
export const SCHEDULE_GET_FAIL = "SCHEDULE_GET_FAIL";
export const SCHEDULE_LOADING = "SCHEDULE_POST_LOADING";
export const SCHEDULE_POST_SUCCESS = "SCHEDULE_POST_SUCCESS";
export const SCHEDULE_POST_FAIL = "SCHEDULE_POST_FAIL";
export const WALLET_BALANCE_LOADING = "WALLET_BALANCE_LOADING";
export const WALLET_BALACE_GET_SUCCESS = "WALLET_BALANCE_LOAD_SUCCESS";
export const WALLET_BALANCE_GET_FAILURE = "WALLET_BALANCE_GET_FAILURE";

export const TAX_GET_SUCCESS = "TAX_GET_SUCCESS";
export const TAX_GET_FAIL = "TAX_GET_FAIL";
export const TAX_LOADING = "TAX_LOADING";
export const TAX_POST_SUCCESS = "TAX_POST_SUCCESS";
export const TAX_POST_FAIL = "TAX_POST_FAIL";
export const TAX_PATCH_SUCCESS = "TAX_PATCH_SUCCESS";
export const TAX_PATCH_FAIL = "TAX_PATCH_FAIL";

export const VIDEOS_GET_SUCCESS = "VIDEOS_GET_SUCCESS";
export const SINGLEVIDEO_GET_SUCCESS = "SINGLEVIDEO_GET_SUCCESS";
export const VIDEOS_GET_FAIL = "VIDEOS_GET_FAIL";
export const VIDEOS_LOADING = "VIDEOS_LOADING";
export const VIDEOS_POST_SUCCESS = "VIDEOS_POST_SUCCESS";
export const VIDEOS_POST_FAIL = "VIDEOS_POST_FAIL";
export const VIDEOS_PATCH_SUCCESS = "VIDEOS_PATCH_SUCCESS";
export const VIDEOS_PATCH_FAIL = "VIDEOS_PATCH_FAIL";


export const PLAYLIST_GET_SUCCESS = "PLAYLIST_GET_SUCCESS";
export const SINGLEPLAYLIST_GET_SUCCESS = "SINGLEPLAYLIST_GET_SUCCESS";
export const PLAYLIST_GET_FAIL = "PLAYLIST_GET_FAIL";
export const PLAYLIST_LOADING = "PLAYLIST_LOADING";
export const PLAYLIST_POST_SUCCESS = "PLAYLIST_POST_SUCCESS";
export const PLAYLIST_POST_FAIL = "PLAYLIST_POST_FAIL";
export const PLAYLIST_PATCH_SUCCESS = "PLAYLIST_PATCH_SUCCESS";
export const PLAYLIST_PATCH_FAIL = "PLAYLIST_PATCH_FAIL";
export const FINES_GET_SUCCESS = "FINES_GET_SUCCESS";
export const FINES_GET_FAIL = "FINES_GET_FAIL";
export const FINES_LOADING = "FINES_LOADING";
export const FINES_POST_SUCCESS = "FINES_POST_SUCCESS";
export const FINES_POST_FAIL = "FINES_POST_FAIL";
export const FINES_PATCH_SUCCESS = "FINES_PATCH_SUCCESS";
export const FINES_PATCH_FAIL = "FINES_PATCH_FAIL";
